WWW_ROOT=/var/www/html                 # Web server document root
HRM_HOME=$WWW_ROOT/hrm                 # HRM root (home) folder
HRM_CONFIG=$HRM_HOME/config            # HRM configuration folder
HRM_SAMPLES=$HRM_HOME/config/samples   # HRM configuration samples folder
HRM_RESRC=$HRM_HOME/resources          # HRM resources folder
HRM_SETUP=$HRM_HOME/setup              # HRM setup folder
HRM_BIN=$HRM_HOME/bin                  # HRM executables folder
HRM_USER=$HRM_HOME/user                # HRM customization folder
HRM_LOG=/var/log/hrm                   # HRM logging folder
HRM_DATA=/data/hrm_data                # HRM data folder
